config/routes.rb
Rails.application.routes.draw do

  resources :video_orders
  get 'admin/users' => 'admin_dashboard#users'
  get 'admin/sellers' => 'admin_dashboard#sellers'
  get 'admin/buyers' => 'admin_dashboard#buyers'
  get 'admin/orders' => 'admin_dashboard#orders'
  get 'admin/listings' => 'admin_dashboard#listings'
  get 'admin/analytics' => 'admin_dashboard#website_analytics'




  resources :admin_dashboard
  # resources :stripe_accounts
  # resources :user_listings
  mount StripeEvent::Engine, at: '/stripe-events' # provide a custom path


  authenticated :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end

  devise_for :buyers
  resources :orders
  devise_for :users, controllers: { confirmations: 'confirmations' }

  resources :users

  resources :users do
    resources :stripe_accounts
  end

  resources :stripe_accounts do
    resources :bank_accounts
  end

  resources :orders do
    resources :video_orders
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :listings do
    resources :orders
end

  resources :users do
    resources :orders
  end

resources :bank_accounts

  resources :orders do
    member do
      patch :charge_update
      put :charge_update
    end
  end


  get 'stripe_show' => "stripe_accounts#show"


  get 'stripe_' => "stripe_account#create"

  get 'stripe_new' => "stripe_account#new"

  get 'cancel' => "orders#cancel_update"

  # resources :listings do
  #   resources :charges
  # end
  # resources :orders do
  #   resource :charge, only: [:new, :create, :show]
  # end

  get 'seller' => "listings#seller"
  #
  # resource :orders
  # resolve('Charge') { [:charges] }

  # resource :charges
  # resolve('Charge') { [:orders] }

  # resources :charges
  get 'edit_stripe' => "stripe_accounts#edit"

  # get 'stripe_accounts/full' => "stripe_accounts#full"


  # resources :orders do
  #   resources :charges
  # end


  #new_order_sales_upload post '/orders/:order_ids(.:format) sales_uploads#new'
 get 'sales' => "orders#sales"
 post 'sales' => "orders#sales"

  #post 'sales' => "orders#sales"
  get 'talent' => "listings#listings_page"

  get 'purchases' => "orders#purchases"

  get 'buyer_purchases' => "orders#buyer_purchases"



  get 'dashboard' => "dashboard#dashboard"
  get 'shouts' => "dashboard#tables"
  get 'charts' => "dashboard#charts"
  get 'settings' => "dashboard#settings"
  get 'account' => "dashboard#account"
  get 'payout_destination' => "dashboard#payout_destination"


get 'auth' => "users#index"

get 'stripe' => "listings#stripe"

get 'analytics' => "dashboard#order_analytics"

# post 'charge' => "layouts#charges"
#
# post 'charge' => "listings#show"



  get 'car' => "listings#carousel"

  root to: "listings#index"


# get '/:user_link', to: 'user_listings#show'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  # load_and_authorize_resource
  layout "admin"


  def account

    @balance = Stripe::Balance.retrieve(
      {:stripe_account => current_user.stripe_token}
    )

    # @payout = Stripe::Payout.retrieve(
    #   {:stripe_account => current_user.stripe_token}
    # )

    @transaction = Stripe::BalanceTransaction.all(
      {
        :limit => 10,
        type: 'payment',
        available_on: { gt: Time.now.to_i },
      },
        { stripe_account: current_user.stripe_token }
    )

    @transaction_1 = Stripe::BalanceTransaction.all(
      {
        :limit => 1,
        type: 'payment',
        available_on: { gt: Time.now.to_i },
      },
        { stripe_account: current_user.stripe_token }
    )

    @transfer = Stripe::Transfer.list(
      {
        limit: 100
      },
      {stripe_account: current_user.stripe_token}
    )

    @payments = Stripe::Charge.list(
      {
        limit: 100, # The number of charges to retrieve (between 1 and 100)
        expand: ['data.source_transfer', 'data.application_fee'] # Expand other objects for additional detail
      },
      { stripe_account: current_user.stripe_token } # The Stripe ID of the user viewing the dashboard
    )

    @payouts = Stripe::Payout.list(
      {
        limit: 100,
        expand: ['data.destination'] # Get some extra detail about the bank account
      },
      { stripe_account: current_user.stripe_token } # Again, authenticating with the ID of the connected account
    )

    @payout_1 = Stripe::Payout.list(
      {
        limit: 1,
        expand: ['data.destination'] # Get some extra detail about the bank account
      },
      { stripe_account: current_user.stripe_token } # Again, authenticating with the ID of the connected account
    )



  end

  def payout_destination

    @txns = Stripe::BalanceTransaction.list(
      {
        payout: params[:id], # The ID of the payout you want transactions for
        expand: ['data.source.source_transfer'], # Expand the source_transfer for extra detail
        limit: 100
      },
      { stripe_account: current_user.stripe_token }
    )

  end


  def settings
    @user = current_user
    @stripe_account = current_user.stripe_account
  end

  def order_analytics
    @orders_referring = Order.joins(:visit).group("referring_domain").count
    @orders_country = Order.joins(:visit).group("city").count
    # @listing_visits = Ahoy::Event.where(name: "Listing Viewed").where_properties(listing_id: current_user).count

  end

  def dashboard

    @orders_a = Order.all.where(seller: current_user).paginate(:page => params[:month_orders_page], :per_page => 12)
    @orders_b = Order.all.where(seller: current_user).paginate(:page => params[:day_orders_page], :per_page => 7)

    @orders_c = Order.all.where(seller: current_user).where("created_at < updated_at").paginate(:page => params[:month_orders_page_1], :per_page => 12)
    @orders_d = Order.all.where(seller: current_user).where("created_at < updated_at").paginate(:page => params[:day_orders_page_1], :per_page => 7)


    @orders_month = @orders_a.all.group_by { |mon|  mon.created_at.beginning_of_month }
    @orders_day = @orders_b.all.group_by { |day|  day.created_at.beginning_of_day }


    @order = Order.new

  end

  def tables

    user = current_user || current_buyer
    orders = Order.where(seller: user)
    orders_with_video = Order.find_by(video: present?)
    orders_charged = orders.where(order_status: [2] )
    orders_created = orders.where(order_status: [1] )


    @orders_tables = orders.order('created_at DESC').paginate(:page => params[:all_orders_page], :per_page => 15)
    @orders_tables_comp = orders_charged.order('created_at DESC').paginate(:page => params[:comp_orders_page], :per_page => 8)
    @orders_tables_up = orders_created.order('created_at DESC').paginate(:page => params[:up_orders_page], :per_page => 8)

  end

  def charts
    @orders = Order.all.where(seller: current_user).paginate(:page => params[:page], :per_page => 15) || @orders = Order.all.where(seller: current_buyer).paginate(:page => params[:page], :per_page => 15)
    @orders_month = @orders.group_by { |mon| mon.created_at.beginning_of_month }



  end


end

app/helpers/dashboard_helper.rb
module DashboardHelper

  def as_table_row(value)
    return "#{value}"
  end

  def as_table_row_transfer(value)
    return "#{value}"
  end

  def as_table_row_transaction(value)
    return "#{value}"
  end

  def as_table_row_payout(value)
    return "#{value}"
  end

  def as_table_row_payment(value)
    return "#{value}"
  end

end

app/views/dashboard/account.html.erb
<link href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css' rel='stylesheet' />

                  <div class="row">
                    <div class="col-md-4">
                        <div class="card ">
                            <div class="card-header ">
                              <% @transaction_1.data.each do |transaction| %>
                                <h4 class="card-title">Next Scheduled Payout</h4>
                                <p class="card-category">Estimated Date: <%= as_table_row_transaction(Time.at(transaction["available_on"]).strftime('%B, %d, %Y on %A')) %></p>
                            </div>
                            <div class="card-body ">
                                  <h1>
                                      <td><%= number_to_currency(as_table_row_transaction(transaction["amount"] / 100.00 )) %></td>
                                      <td><%= as_table_row_transaction(transaction["currency"]).upcase %></td>
                                  </h1>
                              <% end %>
                            </div>
                        </div>
                      </div>
                      <div class="col-md-4">
                          <div class="card ">
                              <div class="card-header ">
                                  <h4 class="card-title">Account Balance</h4>
                                  <p class="card-category">Your account balance pending settlement</p>
                              </div>
                              <div class="card-body ">
                                <% @balance.pending.each do |balance| %>
                                    <h1><%= number_to_currency(balance["amount"] / 100.0 )  %></h1>
                                <% end %>
                              </div>
                          </div>
                      </div>
                      <div class="col-md-4">
                          <div class="card ">
                              <div class="card-header ">
                                <% @payout_1.each do |payout| %>
                                  <h4 class="card-title">Payouts</h4>
                                  <p class="card-category">Deposited on <%= as_table_row_payout(Time.at(payout["arrival_date"]).strftime('%B, %d, %Y')) %></p>
                              </div>
                              <div class="card-body ">
                                            <h1>
                                                <td><%= number_to_currency(as_table_row_payout(payout["amount"] / 100.00 )) %></td>
                                                <td><%= as_table_row_payout(payout["currency"]).upcase %></td>
                                            </h1>
                                        <% end %>
                                    </tbody>
                                </table>
                              </div>
                          </div>
                      </div>
                      <div class="col-md-6">
                          <div class="card ">
                              <div class="card-header ">
                                  <h4 class="card-title">Scheduled Payouts</h4>
                                  <p class="card-category">Your scheduled payouts</p>
                              </div>
                              <div class="card-body ">
                                <table class="table table-bordered table-striped table-hover">
                                    <thead>
                                        <tr>
                                            <!-- <th>Currency</th> -->
                                            <th>Amount</th>
                                            <th>Available On (est.)</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <% @transaction.data.each do |transaction| %>
                                            <tr>
                                                <!-- <td><%= as_table_row_transaction(transaction["currency"]).upcase %></td> -->
                                                <td><%= number_to_currency(as_table_row_transaction(transaction["amount"] / 100.00 )) %></td>
                                                <!-- <td><%= as_table_row_transaction(transaction["type"]) %></td> -->
                                                <td><%= as_table_row_transaction(Time.at(transaction["available_on"]).strftime('%m/%d/%Y')) %></td>
                                            </tr>
                                        <% end %>
                                        <!-- <%= @transaction %> -->
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card ">
                            <div class="card-header ">
                                <h4 class="card-title">Payouts</h4>
                                <p class="card-category">Your past payouts</p>
                            </div>
                            <div class="card-body ">
                              <table class="table table-bordered table-striped table-hover">
                                  <thead>
                                      <tr>
                                          <!-- <th>Currency</th> -->
                                          <th>Amount</th>
                                          <th>Deposited</th>
                                      </tr>
                                  </thead>
                                  <tbody>
                                      <% @payouts.each do |payout| %>
                                          <tr>
                                              <!-- <td><%= link_to "View Details" , payout_destination_path(payout.destination) %></td> -->
                                              <!-- <td><%= as_table_row_payout(payout["currency"]) %></td> -->
                                              <td><%= number_to_currency(as_table_row_payout(payout["amount"] / 100.00 )) %></td>
                                              <td><%= as_table_row_payout(Time.at(payout["arrival_date"]).strftime('%m/%d/%Y')) %></td>

                                          </tr>
                                      <% end %>
                                  </tbody>
                              </table>
                            </div>
                            <div class="card-footer ">
                                <hr>
                                <div class="stats">
                                    <p><i class="fa fa-check"></i>View Payout Schedule</p>
                                </div>
                            </div>
                        </div>
                    </div>


            </div>
        </div>
    </div>
</body>

<script type="text/javascript">
        var baseOptions = {
          maintainAspectRatio: false,
          animation: false
          };
</script>

</html>

app/views/dashboard/chart.html.erb
</thead>

<% @orders_month.each do |month, orders| %>
<tbody>
  <tr>
      <td><%= month.strftime("%B") %></td>
      <td class="center"><%= orders.count %></td>
      <td class="center"><%= (orders.sum { |order| order.updated_at.day - order.created_at.day } / orders.count) %> Days</td>


    </td>
  </tr>
  <% end %>
</tbody>

app/views/dashboard/order_analytics.html.erb
  <div class="row">
      <div class="col-md-6">
          <div class="card ">
              <div class="card-header ">
                  <h4 class="card-title">Referring Site Analytics</h4>
                      <p class="card-category"></p>
                          <table class="table">
                              <thead>
                                  <tr>
                                      <th class="center">Referring Site</th>
                                      <th class="center">Count</th>
                                  </tr>
                              </thead>
                              <% @orders_referring.each do |referring_domain, count| %>
                              <tbody>
                                  <tr>
                                    <td class="center"><%= referring_domain %></td>
                                    <td class="center"><%= count %></td>
                                  </tr>
                            <% end %>
                              </tbody>
                          </table>
                  </div>
            </div>
      </div>
      <div class="col-md-6">
          <div class="card ">
              <div class="card-header ">
                  <h4 class="card-title">Location Analytics</h4>
                      <p class="card-category"></p>
                          <table class="table">
                              <thead>
                                  <tr>
                                      <th class="center">Country</th>
                                      <th class="center">Count</th>
                                  </tr>
                              </thead>
                              <% @orders_country.each do |country, count| %>
                              <tbody>
                                  <tr>
                                    <td class="center"><%= country %></td>
                                    <td class="center"><%= count %></td>
                                  </tr>
                            <% end %>
                              </tbody>
                          </table>
                  </div>
            </div>
      </div>
 </div>



  </div>



</body>

<script type="text/javascript">
        var baseOptions = {
          maintainAspectRatio: false,
          animation: false
          };
</script>

</html>

app/views/dashboard/settings.html.erb
                  <div class="row">
                      <div class="col-md-12">
                        <div class="card ">
                            <div class="card-header ">
                                <h4 class="card-title">Settings</h4>
                                <p class="card-category"> </p>
                            </div>
                            <div class="card-body">
                              <ul class="flex-container">
                              <div class="row">

                                <a href="/users/edit" class="no-decoration">
                                  <li class="setting-section">
                                    <div class="setting-awesome-font">
                                      <i class="fa fa-user" aria-hidden="true"></i>
                                    </div>
                                    <div class="setting-text">
                                      <h5>Account</h5>
                                      <p>Manage your account login details<p>
                                    </div>
                                  </li>
                                </a>
                                <% if current_user.stripe_account %>
                                <%= link_to user_stripe_account_path(@user, @stripe_account) do %>
                                  <li class="setting-section">
                                    <div class="setting-awesome-font">
                                      <i class="fa fa-credit-card" aria-hidden="true"></i>
                                    </div>
                                    <div class="setting-text">
                                      <h5>Payout Settings</h5>
                                      <p>Enable and manage your payout settings and details<p>
                                    </div>
                                  </li>
                                  <% end %>
                                  <% else current_user.stripe_account? %>
                                  <%= link_to new_user_stripe_account_path(@user) do %>
                                    <li class="setting-section">
                                      <div class="setting-awesome-font">
                                        <i class="fa fa-credit-card" aria-hidden="true"></i>
                                      </div>
                                      <div class="setting-text">
                                        <h5>Payout Settings</h5>
                                        <p>Enable and manage your payout settings and details<p>
                                      </div>
                                    </li>
                                    <% end %>
                                    <% end %>

                                <a href="/account" class="no-decoration">
                                  <li class="setting-section">
                                    <div class="setting-awesome-font">
                                      <i class="fa fa-money" aria-hidden="true"></i>
                                    </div>
                                    <div class="setting-text">
                                      <h5>Payout History</h5>
                                      <p>View all past payments to your account<p>
                                    </div>
                                  </li>
                                </a>


                            </div>
                              </div>

                        </div>
                    </div>
                  </div>




                            </div>
                        </div>
                    </div>
                </div>
            <!-- </div>
        </div>
    </div>
  </div> -->

</body>

<script type="text/javascript">
        var baseOptions = {
          maintainAspectRatio: false,
          animation: false
          };
</script>

</html>

app/views/dashboard/upload.html.erb
                    <div class="row">

                      <div class="col-md-6">
                          <div class="card strpied-tabled-with-hover">
                              <div class="card-header ">
                                  <h4 class="card-title">Your Shouts</h4>
                                  <p class="card-category">You can view and take action on your Shouts here.</p>
                              </div>
                              <div class="card-body table-full-width table-responsive">
                                <div class="padding_5">

                                <p id="notice"><%= notice %></p>

                                <p>
                                  <strong>Name:</strong>
                                  <%= @order.name %>
                                </p>

                                <p>
                                  <strong>Description:</strong>
                                  <%= @order.description %>
                                </p>


                                <%= link_to 'Edit', edit_listing_order_path(@order) %> |
                                <%= link_to 'Back', orders_path %>
                                </div>


                              </div>
                          </div>
                      </div>


                        <div class="col-md-6">
                            <div class="card strpied-tabled-with-hover">
                                <div class="card-header ">
                                    <h4 class="card-title">Your Shouts</h4>
                                    <p class="card-category">You can view and take action on your Shouts here.</p>
                                </div>
                                <div class="card-body table-full-width table-responsive">
                                  <%= form_for([@listing, @order]) do |form| %>


                                    <% if order.errors.any? %>
                                      <div id="error_explanation">
                                        <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

                                        <ul>
                                        <% order.errors.full_messages.each do |message| %>
                                          <li><%= message %></li>
                                        <% end %>
                                        </ul>
                                      </div>
                                    <% end %>

                                  <% if user_signed_in? %>
                                  <div class="field">

                                    <%= form.file_field :video %>
                                  </div>


                                  <!-- ADD EDITING -->

                                  <div class="actions">
                                    <%= form.submit "Upload", class: "btn btn-success"  %>
                                  </div>
                                  <% end %>
                                  <% end %>

                                </div>
                            </div>
                        </div>



                        <div class="col-md-12">

            <footer class="footer">
                <div class="container">
                    <nav>
                        <ul class="footer-menu">
                            <li>
                                <a href="#">
                                    Home
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Company
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Portfolio
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Blog
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-center">
                            ©
                            <script>
                                document.write(new Date().getFullYear())
                            </script>
                            <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                        </p>
                    </nav>
                </div>
            </footer>
        </div>
    </div>
    <!--   -->
    <!-- <div class="fixed-plugin">
    <div class="dropdown show-dropdown">
        <a href="#" data-toggle="dropdown">
            <i class="fa fa-cog fa-2x"> </i>
        </a>

        <ul class="dropdown-menu">
			<li class="header-title"> Sidebar Style</li>
            <li class="adjustments-line">
                <a href="javascript:void(0)" class="switch-trigger">
                    <p>Background Image</p>
                    <label class="switch">
                        <input type="checkbox" data-toggle="switch" checked="" data-on-color="primary" data-off-color="primary"><span class="toggle"></span>
                    </label>
                    <div class="clearfix"></div>
                </a>
            </li>
            <li class="adjustments-line">
                <a href="javascript:void(0)" class="switch-trigger background-color">
                    <p>Filters</p>
                    <div class="pull-right">
                        <span class="badge filter badge-black" data-color="black"></span>
                        <span class="badge filter badge-azure" data-color="azure"></span>
                        <span class="badge filter badge-green" data-color="green"></span>
                        <span class="badge filter badge-orange" data-color="orange"></span>
                        <span class="badge filter badge-red" data-color="red"></span>
                        <span class="badge filter badge-purple active" data-color="purple"></span>
                    </div>
                    <div class="clearfix"></div>
                </a>
            </li>
            <li class="header-title">Sidebar Images</li>

            <li class="active">
                <a class="img-holder switch-trigger" href="javascript:void(0)">
                    <img src="../assets/img/sidebar-1.jpg" alt="" />
                </a>
            </li>
            <li>
                <a class="img-holder switch-trigger" href="javascript:void(0)">
                    <img src="../assets/img/sidebar-3.jpg" alt="" />
                </a>
            </li>
            <li>
                <a class="img-holder switch-trigger" href="javascript:void(0)">
                    <img src="..//assets/img/sidebar-4.jpg" alt="" />
                </a>
            </li>
            <li>
                <a class="img-holder switch-trigger" href="javascript:void(0)">
                    <img src="../assets/img/sidebar-5.jpg" alt="" />
                </a>
            </li>

            <li class="button-container">
                <div class="">
                    <a href="http://www.creative-tim.com/product/light-bootstrap-dashboard" target="_blank" class="btn btn-info btn-block btn-fill">Download, it's free!</a>
                </div>
            </li>

            <li class="header-title pro-title text-center">Want more components?</li>

            <li class="button-container">
                <div class="">
                    <a href="http://www.creative-tim.com/product/light-bootstrap-dashboard-pro" target="_blank" class="btn btn-warning btn-block btn-fill">Get The PRO Version!</a>
                </div>
            </li>

            <li class="header-title" id="sharrreTitle">Thank you for sharing!</li>

            <li class="button-container">
				<button id="twitter" class="btn btn-social btn-outline btn-twitter btn-round sharrre"><i class="fa fa-twitter"></i> · 256</button>
                <button id="facebook" class="btn btn-social btn-outline btn-facebook btn-round sharrre"><i class="fa fa-facebook-square"></i> · 426</button>
            </li>
        </ul>
    </div>
</div>
 -->
</body>

</html>