config/routes.rb
Rails.application.routes.draw do

  resources :video_orders
  get 'admin/users' => 'admin_dashboard#users'
  get 'admin/sellers' => 'admin_dashboard#sellers'
  get 'admin/buyers' => 'admin_dashboard#buyers'
  get 'admin/orders' => 'admin_dashboard#orders'
  get 'admin/listings' => 'admin_dashboard#listings'
  get 'admin/analytics' => 'admin_dashboard#website_analytics'




  resources :admin_dashboard
  # resources :stripe_accounts
  # resources :user_listings
  mount StripeEvent::Engine, at: '/stripe-events' # provide a custom path


  authenticated :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end

  devise_for :buyers
  resources :orders
  devise_for :users, controllers: { confirmations: 'confirmations' }

  resources :users

  resources :users do
    resources :stripe_accounts
  end

  resources :stripe_accounts do
    resources :bank_accounts
  end

  resources :orders do
    resources :video_orders
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :listings do
    resources :orders
end

  resources :users do
    resources :orders
  end

resources :bank_accounts

  resources :orders do
    member do
      patch :charge_update
      put :charge_update
    end
  end


  get 'stripe_show' => "stripe_accounts#show"


  get 'stripe_' => "stripe_account#create"

  get 'stripe_new' => "stripe_account#new"

  get 'cancel' => "orders#cancel_update"

  # resources :listings do
  #   resources :charges
  # end
  # resources :orders do
  #   resource :charge, only: [:new, :create, :show]
  # end

  get 'seller' => "listings#seller"
  #
  # resource :orders
  # resolve('Charge') { [:charges] }

  # resource :charges
  # resolve('Charge') { [:orders] }

  # resources :charges
  get 'edit_stripe' => "stripe_accounts#edit"

  # get 'stripe_accounts/full' => "stripe_accounts#full"


  # resources :orders do
  #   resources :charges
  # end


  #new_order_sales_upload post '/orders/:order_ids(.:format) sales_uploads#new'
 get 'sales' => "orders#sales"
 post 'sales' => "orders#sales"

  #post 'sales' => "orders#sales"
  get 'talent' => "listings#listings_page"

  get 'purchases' => "orders#purchases"

  get 'buyer_purchases' => "orders#buyer_purchases"



  get 'dashboard' => "dashboard#dashboard"
  get 'shouts' => "dashboard#tables"
  get 'charts' => "dashboard#charts"
  get 'settings' => "dashboard#settings"
  get 'account' => "dashboard#account"
  get 'payout_destination' => "dashboard#payout_destination"


get 'auth' => "users#index"

get 'stripe' => "listings#stripe"

get 'analytics' => "dashboard#order_analytics"

# post 'charge' => "layouts#charges"
#
# post 'charge' => "listings#show"



  get 'car' => "listings#carousel"

  root to: "listings#index"


# get '/:user_link', to: 'user_listings#show'

end

app/models/video_order.rb
class VideoOrder < ApplicationRecord

  mount_uploader :video, VideoUploader
  serialize :video, JSON

  belongs_to :order

  validates :order_id, uniqueness: true

end

app/controllers/video_orders_controller.rb
class VideoOrdersController < ApplicationController
  before_action :set_video_order, only: [:show, :edit, :update, :destroy]

  # GET /video_orders
  # GET /video_orders.json
  def index
    @video_orders = VideoOrder.all
  end

  # GET /video_orders/1
  # GET /video_orders/1.json
  def show
  end

  # GET /video_orders/new
  def new
    @video_order = VideoOrder.new
  end

  # GET /video_orders/1/edit
  def edit
    @order = @video_order.order_id

  end

  # POST /video_orders
  # POST /video_orders.json
  def create

    @video_order = VideoOrder.new(video_order_params)
    @order = Order.find(params[:order_id])

    @video_order.order_id = @order.id

    respond_to do |format|
      if @video_order.video.present?
          format.html { redirect_to @order, notice: 'Already complete dog!.' }
          format.json { render :show, status: :created, location: @video_order }
        else

      if @video_order.valid?
        begin
          charge = Stripe::Charge.create({
            :amount      => (@order.order_price).to_i * 100,
            :description => 'Rails Stripe customer',
            :currency    => 'usd',
            :customer => @order.stripe_customer_token,
            :destination => {
              :amount => @amount_seller ,
              :account => (@order.seller.stripe_token),
            }
          })
        rescue Stripe::CardError => e
          charge_error = e.message
        end
        if charge_error
          flash[:error] = charge_error
          redirect_to '/'
        else

          if @video_order.save
            format.html { redirect_to @order, notice: 'Video order was successfully created.' }
            format.json { render :show, status: :created, location: @video_order }
          else
            format.html { render :new }
            format.json { render json: @video_order.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end
end

  # PATCH/PUT /video_orders/1
  # PATCH/PUT /video_orders/1.json
  def update
    respond_to do |format|
      if @video_order.update(video_order_params)
        format.html { redirect_to user_order_path([@user, @order]), notice: 'Video order was successfully updated.' }
        format.json { render :show, status: :ok, location: @video_order }
      else
        format.html { render :edit }
        format.json { render json: @video_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_orders/1
  # DELETE /video_orders/1.json
  def destroy
    @video_order.destroy
    respond_to do |format|
      format.html { redirect_to video_orders_url, notice: 'Video order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_order
      @video_order = VideoOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_order_params
      params.require(:video_order).permit(:video, :order_id)
    end
end

app/helpers/video_orders_helper.rb
module VideoOrdersHelper
end

app/views/video_orders/_form.html.erb
<%= form_with(model: video_order, local: true) do |form| %>
  <% if video_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video_order.errors.count, "error") %> prohibited this video_order from being saved:</h2>

      <ul>
      <% video_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/video_orders/edit.html.erb
<h1>Editing Video Order</h1>

<%= render 'form', video_order: @video_order %>

<%= link_to 'Show', @video_order %> |
<%= link_to 'Back', video_orders_path %>

app/views/video_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Video Orders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @video_orders.each do |video_order| %>
      <tr>
        <td><%= link_to 'Show', video_order %></td>
        <td><%= link_to 'Edit', edit_video_order_path(video_order) %></td>
        <td><%= link_to 'Destroy', video_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video Order', new_video_order_path %>

app/views/video_orders/new.html.erb
<h1>New Video Order</h1>

<%= render 'form', video_order: @video_order %>

<%= link_to 'Back', video_orders_path %>

app/views/video_orders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_video_order_path(@video_order) %> |
<%= link_to 'Back', video_orders_path %>